/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculator;

import static javax.swing.JOptionPane.showMessageDialog;


/**
 *
 * @author Jose David
 */
public class UI_v1 extends javax.swing.JFrame {

    /**
     * Creates new form UI_v1
     */
    
    public UI_v1() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfOperacion = new javax.swing.JLabel();
        txtResultado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_Igual = new javax.swing.JButton();
        btn_potencia = new javax.swing.JButton();
        btn_point = new javax.swing.JButton();
        btn_Porc = new javax.swing.JButton();
        btn_Div = new javax.swing.JButton();
        btn_Mult = new javax.swing.JButton();
        btn_Res = new javax.swing.JButton();
        btn_Suma = new javax.swing.JButton();
        btn_C = new javax.swing.JButton();
        btn_Nine = new javax.swing.JButton();
        btn_Eight = new javax.swing.JButton();
        btn_Seven = new javax.swing.JButton();
        btn_Six = new javax.swing.JButton();
        btn_Five = new javax.swing.JButton();
        btn_Four = new javax.swing.JButton();
        btn_Three = new javax.swing.JButton();
        btn_Two = new javax.swing.JButton();
        btn_One = new javax.swing.JButton();
        btn_Zero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfOperacion.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        tfOperacion.setForeground(new java.awt.Color(255, 255, 255));
        tfOperacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(tfOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 320, 52));

        txtResultado.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(255, 255, 255));
        txtResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 320, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 170));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Igual.setBackground(new java.awt.Color(0, 255, 0));
        btn_Igual.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btn_Igual.setText("=");
        btn_Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IgualActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 120, 50));

        btn_potencia.setBackground(new java.awt.Color(255, 102, 0));
        btn_potencia.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btn_potencia.setText("^");
        btn_potencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_potencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_potenciaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_potencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 50, 50));

        btn_point.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btn_point.setText(".");
        btn_point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pointActionPerformed(evt);
            }
        });
        jPanel2.add(btn_point, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 50, 50));

        btn_Porc.setBackground(new java.awt.Color(255, 102, 0));
        btn_Porc.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btn_Porc.setText("%");
        btn_Porc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PorcActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Porc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 50, 50));

        btn_Div.setBackground(new java.awt.Color(255, 102, 0));
        btn_Div.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btn_Div.setText("/");
        btn_Div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DivActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Div, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 50, 50));

        btn_Mult.setBackground(new java.awt.Color(255, 102, 0));
        btn_Mult.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btn_Mult.setText("X");
        btn_Mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MultActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Mult, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 50, 50));

        btn_Res.setBackground(new java.awt.Color(255, 102, 0));
        btn_Res.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btn_Res.setText("-");
        btn_Res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Res, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 50, 50));

        btn_Suma.setBackground(new java.awt.Color(255, 102, 0));
        btn_Suma.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btn_Suma.setText("+");
        btn_Suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SumaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 50, 50));

        btn_C.setBackground(new java.awt.Color(255, 102, 0));
        btn_C.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btn_C.setText("C");
        btn_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CActionPerformed(evt);
            }
        });
        jPanel2.add(btn_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 50, 50));

        btn_Nine.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btn_Nine.setText("9");
        btn_Nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NineActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Nine, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 50, 50));

        btn_Eight.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btn_Eight.setText("8");
        btn_Eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EightActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Eight, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 50, 50));

        btn_Seven.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btn_Seven.setText("7");
        btn_Seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SevenActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Seven, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 50, 50));

        btn_Six.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btn_Six.setText("6");
        btn_Six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SixActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Six, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 50, 50));

        btn_Five.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btn_Five.setText("5");
        btn_Five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FiveActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Five, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 50, 50));

        btn_Four.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btn_Four.setText("4");
        btn_Four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FourActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Four, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 50, 50));

        btn_Three.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btn_Three.setText("3");
        btn_Three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThreeActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Three, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 50, 50));

        btn_Two.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btn_Two.setText("2");
        btn_Two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TwoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Two, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 50, 50));

        btn_One.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btn_One.setText("1");
        btn_One.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OneActionPerformed(evt);
            }
        });
        jPanel2.add(btn_One, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 50, 50));

        btn_Zero.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btn_Zero.setText("0");
        btn_Zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ZeroActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Zero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 50, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 330, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CActionPerformed
        // TODO add your handling code here:
        tfOperacion.setText("");
        txtResultado.setText("");
    }//GEN-LAST:event_btn_CActionPerformed

    private void btn_SevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SevenActionPerformed
        addNumber("7");
    }//GEN-LAST:event_btn_SevenActionPerformed

    private void btn_EightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EightActionPerformed
        // TODO add your handling code here:
        addNumber("8");
    }//GEN-LAST:event_btn_EightActionPerformed

    private void btn_NineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NineActionPerformed
        // TODO add your handling code here:
        addNumber("9");
    }//GEN-LAST:event_btn_NineActionPerformed

    private void btn_FourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FourActionPerformed
        // TODO add your handling code here:
        addNumber("4");
    }//GEN-LAST:event_btn_FourActionPerformed

    private void btn_FiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FiveActionPerformed
        // TODO add your handling code here:
        addNumber("5");
    }//GEN-LAST:event_btn_FiveActionPerformed

    private void btn_SixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SixActionPerformed
        // TODO add your handling code here:
        addNumber("6");
    }//GEN-LAST:event_btn_SixActionPerformed

    private void btn_OneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OneActionPerformed
        // TODO add your handling code here:
        addNumber("1");
    }//GEN-LAST:event_btn_OneActionPerformed

    private void btn_TwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TwoActionPerformed
        // TODO add your handling code here:
        addNumber("2");
    }//GEN-LAST:event_btn_TwoActionPerformed

    private void btn_ThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThreeActionPerformed
        // TODO add your handling code here:
        addNumber("3");
    }//GEN-LAST:event_btn_ThreeActionPerformed

    private void btn_ZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ZeroActionPerformed
        // TODO add your handling code here:
        addNumber("0");
    }//GEN-LAST:event_btn_ZeroActionPerformed

    private void btn_pointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pointActionPerformed
        // TODO add your handling code here:
        addNumber(".");
    }//GEN-LAST:event_btn_pointActionPerformed

    private void btn_potenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_potenciaActionPerformed
        // TODO add your handling code here:
        addNumber("^");
    }//GEN-LAST:event_btn_potenciaActionPerformed

    private void btn_PorcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PorcActionPerformed
        // TODO add your handling code here:
        addNumber("%");
    }//GEN-LAST:event_btn_PorcActionPerformed

    private void btn_DivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DivActionPerformed
        // TODO add your handling code here:
        addNumber("/");
    }//GEN-LAST:event_btn_DivActionPerformed

    private void btn_MultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MultActionPerformed
        // TODO add your handling code here:
        addNumber("*");
    }//GEN-LAST:event_btn_MultActionPerformed

    private void btn_ResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResActionPerformed
        // TODO add your handling code here:
        addNumber("-");
    }//GEN-LAST:event_btn_ResActionPerformed

    private void btn_SumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SumaActionPerformed
        // TODO add your handling code here:
        addNumber("+");
    }//GEN-LAST:event_btn_SumaActionPerformed

    private double GenerateNumber(String source){
        boolean validator = false;
        StringBuilder value = new StringBuilder();
        for(int a = 0; a < source.length(); a++){
            try{
                Integer.parseInt(String.valueOf(source.charAt(a)));
                value.append(String.valueOf(source.charAt(a)));
            }
                
            catch(Exception e){
                if(source.charAt(a) == '.' && !validator){
                    value.append(String.valueOf(source.charAt(a)));
                    validator = true;
                }
                else{
                    showMessageDialog(null, value + " No es un numero! ");
                    return 0;
                }
            }
                    
        }
        return Double.parseDouble(value.toString());
    }

    private void btn_IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IgualActionPerformed
        String aux = this.tfOperacion.getText();
        double value1 = 0;
        double value2 = 0;
        StringBuilder auxiliar = new StringBuilder();
        boolean seccondValue = false;
        boolean symbol = false;
        char operator = 'e';
        for(int x = 0; x < aux.length(); x++){
            char isOperator = 'f';
            if((aux.charAt(x) != '+')&&(aux.charAt(x) != '*')&&(aux.charAt(x) != '-')&&(aux.charAt(x) != '/')&&(aux.charAt(x) != '^')){
                isOperator = 'f';
            }
            else{
                isOperator = 't';
            }
            switch(isOperator){
                case 't' -> {
                    operator = aux.charAt(x);
                    symbol = true;
                }
                case 'f' -> {
                    auxiliar.append(String.valueOf(aux.charAt(x)));
                }    
            }

            if(!seccondValue && symbol){
                    value1 = this.GenerateNumber(auxiliar.toString());
                    showMessageDialog(null, "GENERO VALUE 1 COMO  "+ String.valueOf(value1));
                    symbol = false;
                    seccondValue = true;
                    auxiliar.delete(0,auxiliar.length());
            }
            else if(seccondValue && (x == aux.length()-1)){
                    value2 = this.GenerateNumber(auxiliar.toString());
                    showMessageDialog(null, "GENERO VALUE 2 COMO  "+ String.valueOf(value2));
            }
            
        }
        
        switch(operator){
            case '+' -> {
                
                this.txtResultado.setText(String.valueOf((value1 + value2)));
            }
            case '*' -> {
                this.txtResultado.setText(String.valueOf((value1 * value2)));
            }
            case '-' -> {
                this.txtResultado.setText(String.valueOf((value1 - value2)));
            }
            case '/' -> {
                if(value2 != 0){
                    this.txtResultado.setText(String.valueOf((value1 / value2)));
                }
                else{
                    this.txtResultado.setText("indeterminado");
                }
            }
            case '^' -> {
                this.txtResultado.setText(String.valueOf((Math.pow(value1, value2))));
            }
            default -> {
                    this.txtResultado.setText("Something went wrong");
            }
            
        }

    }//GEN-LAST:event_btn_IgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_v1().setVisible(true);
            }
        });
    }
    
    public void addNumber(String digito){
        tfOperacion.setText(tfOperacion.getText() + digito);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_C;
    private javax.swing.JButton btn_Div;
    private javax.swing.JButton btn_Eight;
    private javax.swing.JButton btn_Five;
    private javax.swing.JButton btn_Four;
    private javax.swing.JButton btn_Igual;
    private javax.swing.JButton btn_Mult;
    private javax.swing.JButton btn_Nine;
    private javax.swing.JButton btn_One;
    private javax.swing.JButton btn_Porc;
    private javax.swing.JButton btn_Res;
    private javax.swing.JButton btn_Seven;
    private javax.swing.JButton btn_Six;
    private javax.swing.JButton btn_Suma;
    private javax.swing.JButton btn_Three;
    private javax.swing.JButton btn_Two;
    private javax.swing.JButton btn_Zero;
    private javax.swing.JButton btn_point;
    private javax.swing.JButton btn_potencia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel tfOperacion;
    private javax.swing.JLabel txtResultado;
    // End of variables declaration//GEN-END:variables
}
